# Generated by Django 3.1.1 on 2020-09-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sanats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='symbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolName', models.CharField(max_length=50)),
                ('symbolID', models.CharField(max_length=50)),
                ('symbolActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceDate', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('hight', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('low', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('adjClose', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('volume', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('count', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('close', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('symbol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symbols')),
            ],
        ),
    ]
