# Generated by Django 3.1.1 on 2020-10-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_prices_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('haghighiBuyVolume', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('hoghooghiBuyVolume', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('haghighiSellVolume', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('hoghooghiSellVolume', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('haghighiBuyCount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('hoghooghiBuyCount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('haghighiSellCount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('hoghooghiSellCount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('symbol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symbols')),
            ],
        ),
        migrations.CreateModel(
            name='BuySell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('buyCount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('buyVolue', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('buyPrice', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('sellCount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('sellVolue', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('sellPrice', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('symbol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symbols')),
            ],
        ),
    ]
