# Generated by Django 3.1.1 on 2020-10-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_buysell_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='symbols_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('groupName', models.CharField(max_length=50)),
                ('baseVol', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('eps', models.IntegerField(default=0)),
                ('sahamCount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('minValidPrice', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('maxValidPrice', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('MinWeek', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('MaxWeek', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('MinYear', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('MaxYear', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('monthlyAvgVol', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('group_pe', models.IntegerField(default=0)),
                ('pe', models.IntegerField(default=0)),
                ('shenavar', models.IntegerField(default=0)),
                ('symbol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symbols')),
            ],
        ),
    ]
