# Generated by Django 3.1.1 on 2020-10-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_symbols_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols_info',
            name='eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='group_pe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='pe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
