# Generated by Django 3.1.1 on 2020-10-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201023_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols_info',
            name='shenavar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
