# Generated by Django 3.1.1 on 2020-10-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201023_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols_info',
            name='shenavar',
            field=models.IntegerField(default=0),
        ),
    ]
