# Generated by Django 3.1.1 on 2020-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201023_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols_info',
            name='eps',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
