# Generated by Django 3.1.1 on 2020-10-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201024_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols_info',
            name='group_pe',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='pe',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
    ]
