# Generated by Django 3.1.1 on 2020-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201024_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols_info',
            name='baseVol',
            field=models.DecimalField(decimal_places=13, default=0, max_digits=16),
        ),
    ]
