# Generated by Django 3.1.1 on 2020-10-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201024_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols_info',
            name='MaxWeek',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='MaxYear',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='MinWeek',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='MinYear',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='baseVol',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='group_pe',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='maxValidPrice',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='minValidPrice',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='monthlyAvgVol',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='sahamCount',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20),
        ),
    ]
