# Generated by Django 3.1.1 on 2020-10-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201024_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols_info',
            name='sahamCount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
