# Generated by Django 3.1.1 on 2020-10-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201024_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols_info',
            name='MaxWeek',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='MaxYear',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='MinWeek',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='MinYear',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='baseVol',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='maxValidPrice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='minValidPrice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='monthlyAvgVol',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='symbols_info',
            name='sahamCount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
